### ISSUE TITLE
Lighty Registration to Netconf Server fails

### ISSUE THREAD

**Issue by guraybaydur** [PANTHEONtech/lighty#1004]
**Describe the bug**
I am using 3gpp yang models [link](https://forge.3gpp.org/rep/sa5/MnS/tree/Rel17-draft/yang-models) and when I boot up an example netconf server with those yang files, lighty gives errors although the netconf server seems connected. 

**Branch**
lighty.io branch 16.x

**To Reproduce**
1. Clone lighty repo
2. git checkout 16.x
3. cd lighty
4. build the project using mvn clean install
5. go to target directory cd lighty-examples/lighty-community-restconf-netconf-app/target
6. unzip example application bundle unzip lighty-community-restconf-netconf-app-16.1.0-SNAPSHOT-bin.zip
7. go to unzipped application directory cd lighty-community-restconf-netconf-app-16.1.0-SNAPSHOT
8. start controller example controller application java -jar lighty-community-restconf-netconf-app-16.1.0-SNAPSHOT.jar
9. Register netconf server to lighty using localhost from Postman
10. See the error

**Expected behavior**
No error logs need to be observed in lighty logs. But encountered errors. Error logs can be seen in https://github.com/guraybaydur/lighty-error-repo/blob/main/lighty_logs

**Screenshots**
![errorlighty](https://user-images.githubusercontent.com/6615115/171879008-df4ad3a3-1885-48a6-b833-2f9904225c60.png)

![image](https://user-images.githubusercontent.com/6615115/171878953-47052bc9-29e7-4b26-a3fe-deb870923bf2.png)

**Environment (please complete the following information):**
 - OS: Linux ubuntu 5.13.0-44-generic 49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Java Version openjdk version "11.0.15" 2022-04-19
 - Maven version Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.15, vendor: Private Build, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.13.0-44-generic", arch: "amd64", family: "unix"

**Comment by ihrasko** [comment]
Hi, you have probably hit the: https://jira.opendaylight.org/browse/YANGTOOLS-1436 issue.

**Comment by guraybaydur** [comment]
Hi, @ihrasko 

You are probably right I converted type leafref to type string in a leaf and error for that leaf is gone. 

So need to wait for this [issue](https://jira.opendaylight.org/browse/YANGTOOLS-1436) is solved right?

BR 
Güray

**Comment by ihrasko** [comment]
Yes, need to wait for the issue to be solved.
When available we will bump to fixed version as soon as possible.

**Comment by ihrasko** [comment]
Hi, the fix for https://jira.opendaylight.org/browse/YANGTOOLS-1436 is included in Lighty.io 16.2.0.
Enjoy!
