### ISSUE TITLE
Test lighty-rcgnmi package (v16.1.0) with the cnf-testsuite

### ISSUE THREAD

**Issue by PeterSuna** [PANTHEONtech/lighty#1048]
**Describe the bug**
cnf-testsuite show some problematic parts with lighty-rcgnmi helm application. See more in their research repot:
https://github.com/cncf/cnf-testsuite/issues/1562

**Branch**
lighty.io branch [16.1.0]

**To Reproduce**
Steps to reproduce:
https://github.com/cncf/cnf-certification/blob/main/instructions.md#running

**Expected behavior**
Test should pass for the following problems:
 -   FAILED single_process_type
        Recommendation: Using exec might help remove the parent process after executing the java command.
 -   FAILED liveness
        Recommendation: Add liveness probe to deployment spec.
 -   FAILED readiness
        Recommendation: Add readiness probe to deployment spec.
 -   FAILED resource_policies
        Recommendation: Define resource limits in the deployment spec.

**Comment by ihrasko** [comment]
Everything merged. Fixed.
