### ISSUE TITLE
Debian support for official lighty docker image?

### ISSUE THREAD

**Issue by marchest** [PANTHEONtech/lighty#1184]
Hi all,

Are you planning to support debian based docker image for lighty app? If so, could you please kindly share when it can be available?

Regards,

**Comment by marchest** [comment]
Anybody can help ?

**Comment by marchest** [comment]
Hi,
I opened a [PR here ](https://github.com/PANTHEONtech/lighty/pull/1186) for the question that i mentioned above. Could you please merge it ?

**Comment by ihrasko** [comment]
Thank you for your effort. We are not interested in maintaining Debian docker. We believe you can create s separate repo for this and add support for any OD you like.
