### ISSUE TITLE
Integration tests are unstable

### ISSUE THREAD

**Issue by rovarga** [PANTHEONtech/lighty#139]
Running a build, there is a decent change to get across:

> [INFO] [ERROR] Failures: 
[INFO] [ERROR] io.lighty.modules.southbound.netconf.tests.TopologyPluginsTest.testMountDevice(io.lighty.modules.southbound.netconf.tests.TopologyPluginsTest)
[INFO] [ERROR]   Run 1: TopologyPluginsTest.testMountDevice:145 
[INFO] dispatcher.createReconnectingClient(<any>);
[INFO] Wanted 1 time:
[INFO] -> at io.lighty.modules.southbound.netconf.tests.TopologyPluginsTest.testMountDevice(TopologyPluginsTest.java:145)
[INFO] But was 2 times. Undesired invocation:
[INFO] -> at org.opendaylight.netconf.sal.connect.netconf.listener.NetconfDeviceCommunicator.initializeRemoteConnection(NetconfDeviceCommunicator.java:150)

This needs to be investigated and fixed.

**Comment by vainyksi** [comment]
Hi Robert,
I can not reproduce the problem.
On which branch you did you observe the issue?
Can you confirm if it is still valid.

MB

**Comment by vainyksi** [comment]
Can not reproduce the issue, please open the issue when more details available.
