### ISSUE TITLE
Rework test logging

### ISSUE THREAD

**Issue by rovarga** [PANTHEONtech/lighty#147]
Currently we output copious amount of test logs, which is fine for debugging, but usually is completely useless (as the build passes).
Rework test logging by having surefire-plugin redirect console log to files. Those log files need to be stored somewhere -- I believe Travis has some options we could use.

**Comment by jveverka** [comment]
The goal here is to configure surefire-plugin redirect test output to log file in order to have console log of the build 'clean' showing just test status.

**Comment by vainyksi** [comment]
after migrating to Github Actions, the logs should be able to store, according to https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs
