### ISSUE TITLE
lighty-gnmi-device-simulator: cannot perform get operations with multiple predicates in path

### ISSUE THREAD

**Issue by nathanIL** [PANTHEONtech/lighty#1524]
Hi,

using standard openconfig yang models for openconfig-interfaces (and all its dependencies of course), trying to following:

**This works fine:**
`gnmic -a 42.0.0.1:9090 -u admin -p admin --insecure get --path openconfig-interfaces:interfaces/interface[name=TwentyFiveGigE0/0/0/26]/state --encoding json_ietf`

```
[
  {
    "source": "42.0.0.1:9090",
    "timestamp": 1694294409227,
    "time": "1970-01-01T00:28:14.294409227Z",
    "updates": [
      {
        "Path": "openconfig-interfaces:interfaces/interface[name=TwentyFiveGigE0/0/0/26]/state",
        "values": {
          "openconfig-interfaces:interfaces/interface/state": {
            "openconfig-interfaces:state": {
              "admin-status": "DOWN",
              "counters": {
                "carrier-transitions": "0",
                "in-broadcast-pkts": "0",
                "in-discards": "0",
                "in-errors": "0",
                "in-fcs-errors": "0",
                "in-multicast-pkts": "0",
                "in-octets": "0",
                "in-pkts": "0",
                "in-unicast-pkts": "0",
                "in-unknown-protos": "0",
                "out-broadcast-pkts": "0",
                "out-discards": "0",
                "out-errors": "0",
                "out-multicast-pkts": "0",
                "out-octets": "0",
                "out-pkts": "0",
                "out-unicast-pkts": "0"
              },
              "enabled": false,
              "ifindex": 71,
              "last-change": "0",
              "logical": false,
              "loopback-mode": false,
              "mtu": 1514,
              "name": "TwentyFiveGigE0/0/0/26",
              "oper-status": "DOWN",
              "type": "iana-if-type:ethernetCsmacd"
            }
          }
        }
      }
    ]
  }
]
```

**But this one, fails and doesnt return anything:**

`gnmic -a 42.0.0.1:9090 -u admin -p admin --insecure get --path openconfig-interfaces:interfaces/interface[name=TwentyFiveGigE0/0/0/26]/state[enabled=false] --encoding json_ietf`

the only difference is that i added another predicate (enabled=false) to the state element. I'm not sure if its a bug or expected, i spent couple of hours on that, getting all the way into ODL code, so not really sure if thats ODL bug or lighty as this is something very trivial to have.

**Comment by ihrasko** [comment]
Thanks for your report. We have assigned it into our task queue.

**Comment by nathanIL** [comment]
I fixed that locally.

**Comment by ihrasko** [comment]
Are you planing to contribute the fix?

**Comment by Tobianas** [comment]
Hello @nathanIL,

I've investigated the issue you raised, and I was able to replicate the problem you reported using both 'gnmic' and 'lighty-rcgnmi-app.' However, I'd like to ask about the specific use case for this scenario. Are you attempting to retrieve the state of the interface only when it's set to 'enabled=false'? If that's the case, you can achieve this using the following 'gnmic' command:
```
gnmic -a 42.0.0.1:9090 -u admin -p admin --insecure get --path openconfig-interfaces:interfaces/interface[name=TwentyFiveGigE0/0/0/26]/state/enabled --encoding json_ietf
```
This command will return the value of the 'enabled' state, allowing for further differentiation.

**Comment by ihrasko** [comment]
Yes, @Tobianas this issue for me seems to be caused by incorrect usage. @nathanIL IMO you should use `/state/enabled` to retrieve enabled leaf value instead of `/state[enabled=false]`.

`/state[enabled=false]` would work only if `state` is a list with `enabled` key. What is not the case.

Please see https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md and https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-interfaces.yang.

Best,

**Comment by nathanIL** [comment]
@ihrasko , @Tobianas  

let me provide few more examples as the above initial example works properly on real devices conforming to openconfig but not on the simulator. it could be device specific stuff, but i doubt so.

**Comment by nathanIL** [comment]
Eventually ended up needing a much simpler solution, so basically implemented it my own way.
