### ISSUE TITLE
jakarta issues when integrate the module lighty-openapi to springboot 3 

### ISSUE THREAD

**Issue by zjujunge** [PANTHEONtech/lighty#1710]
Hello, when I try to integrate the module lighty-openapi/light-restconf-nb-community to the lighty-controller-springboot-netconf,
When startup the springboot project, init the openApi and restconf,

`@Bean
    OpenApiLighty initOpenApiLight(LightyController lightyController) throws ExecutionException,
            InterruptedException, TimeoutException, LightyLaunchException {
//        RestConfConfiguration restconfConfiguration = RestConfConfigUtils.getRestConfConfiguration(Files.newInputStream(configPath));
        RestConfConfiguration restconfConfiguration = RestConfConfigUtils.getDefaultRestConfConfiguration();
        LightyServerBuilder jettyServerBuilder = new LightyServerBuilder(new InetSocketAddress(
                restconfConfiguration.getInetAddress(), restconfConfiguration.getHttpPort()));
        this.openApi =
                new OpenApiLighty(restconfConfiguration, jettyServerBuilder, lightyController.getServices());
        final boolean openApiStartOk = this.openApi.start()
                .get(modulesConfig.getModuleTimeoutSeconds(), TimeUnit.SECONDS);
        if (!openApiStartOk) {
            shutdown();
            throw new LightyLaunchException("Could not init NetconfSB Plugin");
        }

        Runtime.getRuntime().addShutdownHook(new Thread(this::shutdown));
        return this.openApi;
    }`
 It produce the jakarta version issue:

exception with message: javax/ws/rs/core/Application
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178) ~[spring-beans-6.1.1.jar:6.1.1]

**Comment by ihrasko** [comment]
Hello, can you please share the code via pull request and/or complete log?
Thanks.

**Comment by ychechel** [comment]
It does not work with Spring 3 because Jetty version there is 3.1, and Lighty.io jetty needs to be 2.6.1.
I made it work with latest Spring 2
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.18</version>
	</parent>
