### ISSUE TITLE
Upgrading to major versions in the production

### ISSUE THREAD

**Issue by sezerb** [PANTHEONtech/lighty#1865]
**Question**
I know that lighty stores some data in segmented-journal and snapshots folders. So we backup this data to restore it later on. I can do lighty minor version update while persisting this volume. But when I do major update it breaks.

Example scenario: 

- Register two nodes to lighty-rnc 17.3.0
- Update to 17.4.0 -> it works out as is

- Register two nodes to lighty-rnc 17.3.0
- Update to 18.4.0 -> it does not work with old data (persisted volume)

How do you support data migration between major versions? (migration of segmented-journal and snapshots)

Thanks in advance.

**Comment by ihrasko** [comment]
Thanks for the report. We are checking possibilities.

**Comment by ihrasko** [comment]
Using RESTCONF can be an option for you.
This way you can download and upload the configuration datastore from old system to new one.

**Comment by ihrasko** [comment]
Sure @Tobianas will provide you with the steps.

**Comment by Tobianas** [comment]
Hello @yukuraga and @sezerb, thank you for your report!

In the example scenario you provided, the downloading/uploading of the configuration datastore can be achieved by following these steps:

**On 17.4.0 version** 
1, Start the application
2, Retrieve the configuration datastore using the following CURL command:
```
curl -i -k -u admin:admin -X GET -H "Accept: application/json" http://127.0.0.1:8888/restconf/data?content=config
```
3, From the response, copy the relevant part highlighted in white. If necessary, store it in a folder, as it will be used to set the datastore later.
![image](https://github.com/PANTHEONtech/lighty/assets/46903421/17d8ba07-0d67-45d1-92c0-d797967df2a8)

**On Newer version** 
1, Start the application
2. Post the configuration datastore using the following CURL command, replacing YOUR_RESPONSE_GOES_HERE with the actual configuration data:
```
curl -i -k -u admin:admin -X POST -H "Content-Type: application/yang-data+json" -d '
YOUR_RESPONSE_GOES_HERE
' http://127.0.0.1:8888/restconf/data
```

Here’s an example of how the CURL request might look:
```
curl -i -k -u admin:admin -X POST -H "Content-Type: application/yang-data+json" -d '{
  "network-topology:network-topology": {
    "topology": [
      {
        "topology-id": "topology-netconf",
        "node": [
          {
            "node-id": "test_device",
            "netconf-node-topology:keepalive-delay": 0,
            "netconf-node-topology:login-password-unencrypted": {
              "username": "admin",
              "password": "admin"
            },
            "netconf-node-topology:tcp-only": false,
            "netconf-node-topology:port": 830,
            "netconf-node-topology:host": "127.1.0.1"
          },
          {
            "node-id": "new-node"
          }
        ]
      }
    ]
  }
}' http://127.0.0.1:8888/restconf/data
```

If your datastore configuration is as the example, you should receive a `201 Created` response.
![image](https://github.com/PANTHEONtech/lighty/assets/46903421/3c67c932-802a-4999-a566-a85cd4319ee0)


Feel free to let us know if this was helpful. If you have any further questions or need additional assistance, please let us know. 🙂

**Comment by yukuraga** [comment]
Hello @Tobianas , thank you for the detailed explanation. As @sezerb stated in his first message, our scenario involves backup/restore operation. This means, in our scenario while we are uploading backup data, target datastore is not necessarily empty.

For instance, some data might be downloaded in like 17.4.0 version, then lighty might be upgraded to another major version, and some operator might have done new topology creation and node registration operations. Then after certain time, some other operator might need to upload downloaded data to this datastore intending to replace existing data with the backup data.

In such a scenario, when I try your proposal, I get 409 conflict to POST request.

![image](https://github.com/PANTHEONtech/lighty/assets/23458942/829bb231-4778-4b1c-a675-744d2522d588)

I tried using PUT but noticed that PUT is not allowed. For PATCH, I get no success due to 415 Unsupported Media Type.

**Comment by Tobianas** [comment]
Hello @yukuraga 

In this case, please try modifying the request to `PUT` and change the path from:
 `http://127.0.0.1:8888/restconf/data` 
 to:
 `http://127.0.0.1:8888/restconf/data/network-topology:network-topology` 
 (This is done by adding `/network-topology:network-topology` to the end of the original URL).
If you modified only the `/network-topology` endpoint in your datastore than this should be enough. 
This will overwrite the data stored in `/network-topology`  with your backup data.

Here is and example: (Please note that my scenario has a different port and base path, but that does not affect the result)

I have created only one node called `test_device`
![image](https://github.com/PANTHEONtech/lighty/assets/46903421/fd9af83b-186d-48fa-93db-34fcdfaf0708)
Then i want to PUT two nodes called `test_device1` and `new-node` into the `topology-netconf` (in your case backup data)
![image](https://github.com/PANTHEONtech/lighty/assets/46903421/41c101f1-3f9f-4e7a-b4e4-8324db8cacbd)
I received a `204 No Content` response, which means the request was successful. 
And now when i GET `http://127.0.0.1:8181/rests/data?content=config`, the new desired data can be seen:
![image](https://github.com/PANTHEONtech/lighty/assets/46903421/5e66e5f9-5231-47b6-aded-b7c68046a349)

**Comment by yukuraga** [comment]
Thank you for your support @ihrasko @Tobianas it is ok now.
