### ISSUE TITLE
Connection status keeps as "connected" to NETCONF server although network interface is down

### ISSUE THREAD

**Issue by yukuraga** [PANTHEONtech/lighty#1968]
First of all, I am creating this as question, since I'm not sure whether it is an actual bug or some expected behavior.

Question:

There are two VMs in one of our test setups. In the first VM, lighty.io runs as part of our project in a container, in the second VM there is a NETCONF server running. So, node is successfully added for this NETCONF server via RESTCONF in lighty.io, and we get "connected" when we query node via RESTCONF with ?content=nonconfig.

Then we shut down the interface on the first VM via sudo ip link set ens32 down, and check connectivity from first VM to second VM via ping to see that connectivity is lost. After this, when we check same node query result, we still see that status is "connected". At this state, if we manually restart lighty.io container, then the status comes as "connecting" (as expected).

Do you think this is a bug, or some configuration situation?

Thanks in advance.
Ugur

**Comment by ihrasko** [comment]
Hello,

please check how to set keeplive delay in https://docs.opendaylight.org/projects/netconf/en/latest/user-guide.html.

Depending on netconf version you can be affected by this bug (check also `Linked issues`): https://lf-opendaylight.atlassian.net/browse/NETCONF-1201.

Best,
