### ISSUE TITLE
Problem in SSH connection to the lighty-toaster-device simulator

### ISSUE THREAD

**Issue by maurizio-lazzarini** [PANTHEONtech/lighty#1977]
After correct starting of the lighty-toaster-device simulator I tryed to connect via SSH without problem, but, when the hello xml response was inserted the simulator returns an error message

**Branch**
lighty-netconf-simulator-20.3.0

**To Reproduce**
1.On Ubuntu 24.04 into VirtualBox:  java -jar lighty-toaster-device-20.3.0-SNAPSHOT.jar 12345
2. On Windows command prompt (as administrator): ssh admin@192.168.56.118 -p 12345 -s netconf
3. The resulting answer from simulated device is: 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <capabilities>
        <capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability>
        <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
        <capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability>
        <capability>http://netconfcentral.org/ns/toaster?module=toaster&amp;revision=2009-11-20</capability>
        <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
        <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
        <capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability>
        <capability>urn:ietf:params:netconf:base:1.1</capability>
        <capability>urn:ietf:params:netconf:base:1.0</capability>
    </capabilities>
    <session-id>1</session-id>
</hello>
]]>]]>

4. on the same command prompt window, the hello response was inserted:
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <capabilities>
        <capability>urn:ietf:params:netconf:base:1.0</capability>
    </capabilities>
</hello>
]]>]]>
No answer received

5.  The hello answer was reinserted:
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <capabilities>
        <capability>urn:ietf:params:netconf:base:1.0</capability>
    </capabilities>
</hello>
]]>]]>

6. An error message was received:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <rpc-error>
        <error-type>protocol</error-type>
        <error-tag>unknown-element</error-tag>
        <error-severity>error</error-severity>
        <error-message>Unknown tag hello in message:
&lt;hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"&gt;
    &lt;capabilities&gt;
        &lt;capability&gt;urn:ietf:params:netconf:base:1.0&lt;/capability&gt;
    &lt;/capabilities&gt;
&lt;/hello&gt;
</error-message>
        <error-info>
            <bad-element>hello</bad-element>
        </error-info>
    </rpc-error>
</rpc-reply>
]]>]]>

7. The complete sequence for the SSH session is:
C:\Windows\system32>ssh admin@192.168.56.118 -p 12345 -s netconf
The authenticity of host '[192.168.56.118]:12345 ([192.168.56.118]:12345)' can't be established.
RSA key fingerprint is SHA256:+h00JiOEllq+E3PmBZvx8XL5UCBnbhuYOXrZaNcFw0A.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[192.168.56.118]:12345' (RSA) to the list of known hosts.
admin@192.168.56.118's password:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <capabilities>
        <capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability>
        <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
        <capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability>
        <capability>http://netconfcentral.org/ns/toaster?module=toaster&amp;revision=2009-11-20</capability>
        <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
        <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
        <capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability>
        <capability>urn:ietf:params:netconf:base:1.1</capability>
        <capability>urn:ietf:params:netconf:base:1.0</capability>
    </capabilities>
    <session-id>1</session-id>
</hello>
]]>]]><hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <capabilities>
        <capability>urn:ietf:params:netconf:base:1.0</capability>
    </capabilities>
</hello>
]]>]]>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <capabilities>
        <capability>urn:ietf:params:netconf:base:1.0</capability>
    </capabilities>
</hello>
]]>]]>
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <rpc-error>
        <error-type>protocol</error-type>
        <error-tag>unknown-element</error-tag>
        <error-severity>error</error-severity>
        <error-message>Unknown tag hello in message:
&lt;hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"&gt;
    &lt;capabilities&gt;
        &lt;capability&gt;urn:ietf:params:netconf:base:1.0&lt;/capability&gt;
    &lt;/capabilities&gt;
&lt;/hello&gt;
</error-message>
        <error-info>
            <bad-element>hello</bad-element>
        </error-info>
    </rpc-error>
</rpc-reply>
]]>]]>

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04
 - Java Version 17
 - Maven version 3.9.7

**Comment by Tobianas** [comment]
Thank you for your report
We added this issue to developer queue.

**Comment by maurizio-lazzarini** [comment]
The simulator is working as expected, I made a mistake by transmitting the hello answer two times, this caused the error message received from the simulator. The problem is that I was expecting a message after the transmission of the hello answer, instead the netconf doesn't foreseen any message after the hello phase completion. 

The issue could be closed
