### ISSUE TITLE
Notifications in case of configuration update

### ISSUE THREAD

**Issue by sezerb** [PANTHEONtech/lighty#2014]
I've checked closed issues about _lighty notifications_ and also check ODL latest documentation. It says "_The notifications were not shown using RESTCONF because RESTCONF does not support notifications from **mounted NETCONF devices**._". 

I use lighty-rnc-app and register a netconf server to it. I want to get notifications from this node, but via using rendered RESTCONF end points. For instance when a configuration change occurs in mounted device's configuration, I want to be notified from lighty.io. Is there a generic way of doing it with lighty-rnc-app?

**Comment by ihrasko** [comment]
With some luck this should work in recent lighty.io versions [out-of-the-box](https://docs.opendaylight.org/projects/netconf/en/latest/user-guide.html#receiving-netconf-device-notifications-on-a-http-client).

**Comment by sezerb** [comment]
Hi @ihrasko,

With some luck it seems like it's working out. Following the document helped, but not 100%. I need to have some debugging.

In summary, it is possible to experiment this only via lighty stack.

lighty-rnc-app and lighty-notifications-device are based on 19.4.0 version.
It eases my job to use _openapi_ end points:

1. First create a notification subscription:
![image](https://github.com/user-attachments/assets/c1e276af-1263-4ca1-b9ff-963375ddae29)
Please note that input field is set as empty intentionally.

2. Subscribe to notifications on specified device. Mine is "notif".
![image](https://github.com/user-attachments/assets/56b0e49c-ae9e-4b78-aedd-8d924a9d8cd8)
Response:
![image](https://github.com/user-attachments/assets/5ef3ae4e-79b3-429d-a8e2-0c5b1d26f828)

3. Listen to notifications
`curl -N -H "Accept: text/event-stream" 'http://localhost:8888/restconf/notif/notif?notificationType=device'`
![image](https://github.com/user-attachments/assets/8a0875fc-57e2-4dc8-ad32-f12726396d47)

We can also add this information to README of lighty-notifications-device.

Thanks for your support. We can close the issue.

**Comment by ihrasko** [comment]
Yes, it makes sense.

We welcome your contribution into documentation.

Thanks!

**Comment by ihrasko** [comment]
IMO quick guess lighty.io simulator does not have stream called `NERTCONF` - maybe that's why you have to use empty input. With other devices you have good change to be able to see that stream/or others. For example https://github.com/CESNET/netopeer2.
