### ISSUE TITLE
Not possible to listen to notifications

### ISSUE THREAD

**Issue by ihrasko** [PANTHEONtech/lighty#532]
**Describe the bug**

Even after resolving #531 it is not possible to listen for notifications on URL with returned stream name.

**Branch**
all active branches (web-sockets), master (web-sockets + SSE)

**To Reproduce**

Do the POST request to http://localhost:8888/restconf/operations/sal-remote:create-data-change-event-subscription
with body:

`{ "input": { "path": "/toaster:toaster/toaster:toasterStatus", "sal-remote-augment:datastore": "OPERATIONAL", "sal-remote-augment:scope": "ONE" } }`

Get the response:

`{
    "sal-remote:output": {
        "stream-name": "data-change-event-subscription/toaster:toaster/toasterStatus/datastore=OPERATIONAL/scope=ONE"
    }
}`

Use stream name to listen to notifications with web-sockets:

`wscat -c ws://127.0.0.1:8185/restconf/notif/data-change-event-sucription/toaster:toaster/toasterStatus/datastore=OPERATIONAL/scope=ONE`

You get error:

`error: Unexpected server response: 500`

Error log:

`ERROR [nioEventLoopGroup-8-3] (WebSocketServerHandler.java:87) - Listener for stream with name 'restconf/notif/data-change-event-subscription/toaster:toaster/toasterStatus/datastore=OPERATIONAL/scope=ONE' was not found.`

Use stream name to listen to notifications with SSE:

`curl -X GET http://127.0.0.1:8888/restconf/notif/data-change-event-subscription/toaster:toaster/toasterStatus/datastore=OPERATIONAL/scope=ONE -H "Content-Type: text/event-stream"`

You get error:

`...<body><h2>HTTP ERROR 404 Not Found</h2>...`

There are no logs in console.

**Comment by sezerb** [comment]
Does lighty support RESTCONF notifications for mounted devices? ODL claims that they do not support RESTCONF notifications for mounted devices according to [documentation](https://docs.opendaylight.org/projects/netconf/en/latest/developer-guide.html).

**Comment by ihrasko** [comment]
AFAIC even Lighty.io does not support RESTCONF (as described in RFC) notifications on the device.

But...

Maybe the following programmatically example could help you:
https://github.com/PANTHEONtech/lighty-netconf-simulator/tree/master/examples/devices/lighty-notifications-device

**Comment by ihrasko** [comment]
When removing bierman02 implementation (https://github.com/PANTHEONtech/lighty/pull/1016/files) we have found that the only place where `webSocketPort` was used is `RestconfProviderImpl`. It means that web-socket support was enabled in bierman02 only. After removing bierman02 Lighty.io no more supports web-socket at all (its not implemented).

**Comment by ihrasko** [comment]
No implemented at all - this issue is no more relevant.

**Comment by ihrasko** [comment]
No implemented at all - this issue is no more relevant.
