### ISSUE TITLE
Persistent Configurational Datastore and Mount Points

### ISSUE THREAD

**Issue by Sezerb** [PANTHEONtech/lighty#698]
Hi all,

First of all thanks for your RNC work which is very easy to setup and work on it.

In the architectural view that you provided  for your RNC solution, MD-SAL has configurational and operational datastores.

1- According to my understanding these are reflecting configuration mount points for network devices/services. I'm running a ConfD netconf server. It has also its own configurational and operational datastores. Using the rendered restconf endpoints I can do some basic configurations at the netconf server side. Is it also possible to store these configurations in the MD-SAL's configurational datastores _persistently_ or is it just a mount point? I want to use _SDN Controller_ for both configuration of network services and also for configuration store like a backup. Is it possible?

2- When I check _ODL_ controller example and mount a netconf server, it automatically sends a get-schema request and save the yang module under the cache folder. In lighty.io example I checked the cache folder and could not see the yang module. Am I missing something? Because rendered restconf endpoints are working successfully with lighty.io. (Does it support ietf-network-monitoring?)

Thanks in advance.

**Comment by Pyro2266** [comment]
Hello Sezerb,
 
thank you for your kind words.
 
In a nutshell, two datastores represent state of the controller (lighty.io or ODL).
As the name suggests, the configurational datastore is used to configure controller (note: controller, not devices). This is the place where users apply their configurational "intent". Controller and plugins inside are listening on specific subtrees of configurational datastore and are triggering actions according to the data inserted there.
The operational datastore is a read-only for users and it represents actual state of the controller.
 
So for example, if you want to connect some NETCONF device to the controller, you need to insert device connection data (like address, port, credentials,...) into the right place in the configurational datastore. When you do it, the NETCONF SB plugin takes that data and tries to connect to the device. After that it will write the result of this operation in the operational datastore - there, you can see connection status of the device and some more information.
 
If you want to access data on the device itself, it does not go through controller datastores, but via so called "mountpoint" directly to the device. Device data cache is not supported in the lighty.io RNC 13.2.1 release.
 
Persistency of the configurational datastore is turned on by default. But it is persisted only on a local filesystem (via [segmented-journal](https://github.com/PANTHEONtech/lighty/blob/13.2.1/lighty-resources/singlenode-configuration/src/main/resources/singlenode/factory-akka-default.conf#L122)). So if you start lighty.io RNC app from your IDE or as a _.jar_ file, connect NETCONF device to it, turn app off and start it again, then it will automatically connect to the same NETCONF device.
 
Regarding the cache - yes, lighty.io apps with NETCONF SB plugin are storing YANG models downloaded (via netconf-monitoring) from the NETCONF device in the _cache/schema_ directory.
 
This is what it looks like after I connected our [lighty.io NETCONF simulator](https://github.com/PANTHEONtech/lighty-netconf-simulator) to the lighty.io RNC app:
```
root@samuel-VirtualBox:/lighty-rnc/cache/schema# pwd
/lighty-rnc/cache/schema
root@samuel-VirtualBox:/lighty-rnc/cache/schema# ls -la
total 116
drwxr-xr-x 2 root root  4096 Apr 12 09:59 .
drwxr-xr-x 3 root root  4096 Apr 12 09:58 ..
-rw-r--r-- 1 root root 16829 Apr 12 09:59 ietf-inet-types@2013-07-15.yang
-rw-r--r-- 1 root root 18738 Apr 12 09:59 ietf-netconf-monitoring@2010-10-04.yang
-rw-r--r-- 1 root root 17932 Apr 12 09:59 ietf-yang-types@2013-07-15.yang
-rw-r--r-- 1 root root  2979 Apr 12 09:59 netconf-node-optional@2019-06-14.yang
-rw-r--r-- 1 root root 11477 Apr 12 09:59 netconf-node-topology@2015-01-14.yang
-rw-r--r-- 1 root root  7476 Apr 12 09:59 network-topology-rpcs@2018-03-20.yang
-rw-r--r-- 1 root root 14321 Apr 12 09:59 network-topology@2013-10-21.yang
-rw-r--r-- 1 root root  2556 Apr 12 09:59 notifications@2008-07-14.yang
-rw-r--r-- 1 root root  2388 Apr 12 09:59 yang-ext@2013-07-09.yang
```

We'll be happy to hear more about your use-case - you can contact us directly via [Contact Us](https://lighty.io/contact/) form on the [lighty.io](https://lighty.io) webpage.

**Comment by Sezerb** [comment]
Hi Pyro2266,

Thanks for your very informative message. Here is really valuable information that one cannot find in documentation directly. I've already verified the points you mentioned on my setup.

We are in an investigation phase, and if we have further questions we would like to get in contact with you.

Regards,
Sezerb
