### ISSUE TITLE
java docs for lighty core classes and interfaces 

### ISSUE THREAD

**Issue by KarlGallagher** [PANTHEONtech/lighty#703]
**Question**
How can we help?

Thank you for creating your report! We will get back to you, as soon as possible. Please note, that our support on GitHub is based on a non-guaranteed best effort. As soon as we are able, we will get back to you.
 
If you are in a hurry and have an inquiry regarding commercial support, please via this contact form: https://pantheon.tech/contact-us

Hello,

I am searching for javadocs covering the lighty-core (public)classes and interfaces.  
Are these made available anywhere?

**Comment by mmiklus** [comment]
Dear Karl,

Please let me know if you're looking for any particular class / interface, we'd be happy to improve lighty docs.

Released artifacts can be found on maven central: https://search.maven.org/search?q=g:io.lighty.core
(https://www.javadoc.io/doc/io.lighty.core/lighty-controller/latest/index.html)

Hope this helps.
