### ISSUE TITLE
Lighty.io doesn't support post, if related yang file has multiple key leaf in a list.

### ISSUE THREAD

**Issue by MuhendisBey** [PANTHEONtech/lighty#713]
Lighty.io renders yang endpoint but it doesn't properly work as it said.
Rendered endpoint and input are like this:
![image](https://user-images.githubusercontent.com/10077290/121540548-3c4e0b80-ca0f-11eb-8033-b0066236836e.png)

If i call in this way error message is like this:
![image](https://user-images.githubusercontent.com/10077290/121539357-47ed0280-ca0e-11eb-8828-face69cc7a2f.png)

**Branch**
lighty.io branch [v 14.x]

**To Reproduce**
1. git checkout https://...
2. cd lighty
3. mvn clean install
4. run restconf-netconf example
5. add valid netconf device
6. goto restconf swagger page
7. go to subnet post request
8. make request

**Expected behavior**
user shouldn't get an error.

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Java Version [11]
 - Maven version [3]

**Yang file**:
module dhcpd {

  namespace "http://example.com/ns/example/dhcpd";
  prefix dhcpd;

  import ietf-inet-types {
    prefix inet;
  }

  import tailf-xsd-types {
    prefix xs;
  }

  revision 2019-02-14 {
    description "Normalized YANG identifier names.";
  }

  revision 2018-11-20 {
    description "YANG header information updated";
  }

  revision 2009-05-19 {
    description "Initial revision.";
  }

  typedef loglevel {
    type enumeration {
        enum kern;
        enum mail;
        enum local7;
    }
  }

  grouping subnet {
    list subnet {
      key "net mask";
      leaf net {
        type inet:ipv4-address;
      }
      leaf mask {
        type inet:ipv4-address;
      }
      container range {
        presence "";
        leaf dynamic-bootp {
          type boolean;
          default false;
          description "Enable BOOTP for this instance.";
        }
        leaf low-addr {
          type inet:ipv4-address;
          mandatory true;
          description "Enable BOOTP for this instance.";
        }
        leaf high-addr {
          type inet:ipv4-address;
          description "Enable BOOTP for this instance.";
        }
      }
      leaf routers {
        type string;
      }
      leaf tftpAddrs {
        type string;
      }
      leaf ntpAddrs {
        type string;
      }
      leaf dnsAddrs {
        type string;
      }
      leaf max-lease-time {
        type xs:duration;
        default PT7200S;
      }
      leaf default-lease-time {
        type xs:duration;
        default PT600S;
      }
    }
  }

  container dhcp {
    leaf serverActivity {
        type boolean;
        default true;
    }
    leaf default-lease-time {
      type xs:duration;
      default PT600S;
    }
    leaf max-lease-time {
      type xs:duration;
      default PT7200S;
    }
    leaf log-facility {
      type loglevel;
      default local7;
    }
    container subnets {
      uses subnet;
    }
    container shared-networks {
      list shared-network {
        key name;
        max-elements 1024;
        leaf name {
          type string;
        }
        container subnets {
          uses subnet;
        }
      }
    }
  }
}

**Comment by ihrasko** [comment]
The root cause: https://jira.opendaylight.org/browse/NETCONF-708

**Comment by MuhendisBey** [comment]
ok i saw it issue, so what we do to solve this problem ? do you have patch or workaround solution ?
if ODL guys have a solution(workaround or not), how can i  get it into the lighty.io v14 project ?

Do you have a suggestion?

Many thanks

**Comment by ihrasko** [comment]
I expect that the fix will be available in Lighty 14.2.0.

**Comment by mmiklus** [comment]
@MuhendisBey , thank you for your report. lighty is following Opendaylight release train. You can expect the fix to be included in lighty community release with a new Opendaylight release. lighty versioning is mapped to Opendaylight version semantics (14 = Silicon, 1 - SR1). If this issue is pressing matter of yours, please reach us over https://pantheon.tech/contact-us/ to discuss alternative options.

**Comment by MuhendisBey** [comment]
> netconf-artifacts

Hello Ihrasko many thanks for your answer. I'll test it as as a expr.
to know this step is very good for me.

**Comment by MuhendisBey** [comment]
> @MuhendisBey , thank you for your report. lighty is following Opendaylight release train. You can expect the fix to be included in lighty community release with a new Opendaylight release. lighty versioning is mapped to Opendaylight version semantics (14 = Silicon, 1 - SR1). If this issue is pressing matter of yours, please reach us over https://pantheon.tech/contact-us/ to discuss alternative options.

Hello mmiklus,
I got your point. You follow the ODL, so that, when ODL new release is out, you make a new release.
I got it. So you know the ODL roadmap?, it was written in mail list or something else ?

Many Thanks

**Comment by mmiklus** [comment]
Silicon (14) release schedule: https://docs.opendaylight.org/en/stable-silicon/release-process/release-schedule.html 
Release updates: https://lists.opendaylight.org/g/release/

Cheers
