### ISSUE TITLE
Lighty.io is not Compliant with RFC about Returned Error Message

### ISSUE THREAD

**Issue by MuhendisBey** [PANTHEONtech/lighty#717]
**Describe the bug**
RFC described returned error message like this:
![image](https://user-images.githubusercontent.com/10077290/123235347-737aed00-d4e4-11eb-9388-6cbfe0346d65.png)

but lighty.io response is like this:
![image](https://user-images.githubusercontent.com/10077290/123235423-82fa3600-d4e4-11eb-9519-90370ebfd13b.png)

"error-tag"s are not consistence with each other.

Is this a bug or is there an other RFC which i don't know?

Many Thanks

**Branch**
lighty.io branch [eg. 12.2.x]

**Expected behavior**
Lighty.io should compliant with RFC

**Comment by MuhendisBey** [comment]
I tested it also ODL.
I guess again it's ODL bug, right ?

**Comment by caladi** [comment]
Hello @MuhendisBey,

Yes, this is not the correct behavior. It should be fixed in 13.3.x and 14.0x branches. Please try it at these branches. Branch [12.2.x] is no longer supported.

Please let us know if you have any questions.

**Comment by MuhendisBey** [comment]
Hello @caladi 

Sorry, i wrote wrong branch name, i tested it in 14.0.x branch, and result is like that.

**Comment by MuhendisBey** [comment]
Hello @caladi 

I tested it in new version(15.0.1) of lighty.io and result is like this:
![image](https://user-images.githubusercontent.com/10077290/144042852-288903f7-5dd4-4d4c-acb3-cecb38c8fe4e.png)

I guess, the error-message and error-info which are dynamic parts are completely removed in new version

**Comment by MuhendisBey** [comment]
Hello @caladi 
again me,

if i add custom message. lighty.io insert our custom message, doesn't replace it.
here is the result:
![image](https://user-images.githubusercontent.com/10077290/144046896-db522a00-d7ab-4d6b-8031-f927f5eb0305.png)

here is the yang:
![image](https://user-images.githubusercontent.com/10077290/144046943-1a9b3320-c6c9-42b3-bb91-d3fb3b32b584.png)

**Comment by MuhendisBey** [comment]
Hello @PeterSuna 

Can you try this with version 15.1.0 ?
The expected result is the same or not in version 15.1.0?

**Comment by PeterSuna** [comment]
Hello MuhendisBey,
Yes, the result is same for 15.1.0. As I mention before, I have tested to create existing data inside list.
I have created yang model test-data.yang and add it to lighty-community-restconf-netconf-app :
```
module test-model {

  yang-version 1;
  namespace "test:model:namespace";
  prefix TM;
  revision "2021-11-11";

  container test-container {
    list test-list {
      key list-key;
      leaf list-key {
        type string;
      }
    }
  }
}
```
Then I sent 2x times request:
```
curl --request POST 'http://localhost:8888/restconf/data/test-model:test-container' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
    "test-list": [
        {
            "list-key": "data"
        }
    ]
}'
```
Second request response with:
```
{
    "errors": {
        "error": [
            {
                "error-tag": "data-exists",
                "error-message": "Data already exists",
                "error-path": "/test-model:test-container/test-list[list-key='data']",
                "error-type": "protocol"
            }
        ]
    }
}
```
If this scenario is not what cause your problem, please provide more details how to reproduce this issue.

Thanks

**Comment by ihrasko** [comment]
Fixed in Lighty.io 15.2.0

Enjoy!

**Comment by MuhendisBey** [comment]
Hello @ihrasko 
Many thanks for your effort :-)
