### ISSUE TITLE
Lighty.io doensn't consider error-msg statement in yang file

### ISSUE THREAD

**Issue by MuhendisBey** [PANTHEONtech/lighty#718]
**Describe the bug**
Lighty.io returns default error (or generated by itself) to client.

I have yang file like this:
![image](https://user-images.githubusercontent.com/10077290/123244465-a1642f80-d4ec-11eb-9127-53b86a28190a.png)

If i make request like this:
![image](https://user-images.githubusercontent.com/10077290/123244677-d1133780-d4ec-11eb-94c2-f5b27a62d97a.png)

I got this error:
![image](https://user-images.githubusercontent.com/10077290/123244752-dff9ea00-d4ec-11eb-8042-b5ae8fbac791.png)

But if make request with other netconf client, i got correct error:
![image](https://user-images.githubusercontent.com/10077290/123245020-1f283b00-d4ed-11eb-9510-74c30bbf3dde.png)

**Expected behavior**
We should see error message which is in the yang file

**Comment by MuhendisBey** [comment]
I tested it also ODL.
I guess again it's ODL bug, right ?

**Comment by MuhendisBey** [comment]
related ODL issue: https://jira.opendaylight.org/browse/NETCONF-786

**Comment by caladi** [comment]
Hello @MuhendisBey,

Yes, it's issue related with ODL, but what I saw in the linked jira ticket there is created a patch for this issue.

 Please let us know if you have any questions.

**Comment by MuhendisBey** [comment]
Yeah i opened the issue, then ODL guys solved the problem.
in that case, in lighty.io, i can change the netconf-artifacts version from 1.13.1 to 2.0.0 ?
is that enough  for getting latest update ?

Many Thanks

**Comment by MuhendisBey** [comment]
I followed the this changes: https://lists.opendaylight.org/g/release/message/19936
i changed the  odlparent-9.0.2, infrautils-2.0.2,
yangtools-7.0.3, mdsal-8.0.0, controller-4.0.0 and aaa-0.14.0.
But lighty.io gives an error on lightyControllerImple. It says cannot find symbol.
I guess, there is a work which will be made on the lighty side, right?

**Comment by caladi** [comment]
Hello @MuhendisBey,

There is a new release 14.1.0 scheduled in a few days/weeks. Release should include this changes. Please wait for the new release.
The ODL release can modify APIs, so code need to be changed. Bumping to the new versions could cause unexpected build errors/failures.

Kind Regards

**Comment by ihrasko** [comment]
The latest Lighty.io 15.2.0 contains a fix.

Enjoy!

**Comment by MuhendisBey** [comment]
Hello @ihrasko 
Many thanks for your effort :-)
