### ISSUE TITLE
Release preparation fails on io.lighty.kit.examples.community.CommunityAAARestconfAppTest

### ISSUE THREAD

**Issue by rovarga** [PANTHEONtech/lighty#811]
**Describe the bug**
Attempting mvn release:prepare fails with:
```
[INFO] [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 41.787 s <<< FAILURE! - in io.lighty.kit.examples.community.CommunityAAARestconfAppTest
[INFO] [ERROR] io.lighty.kit.examples.community.CommunityAAARestconfAppTest.readDataCorrectCredentials on readDataCorrectCredentials(io.lighty.kit.examples.community.CommunityAAARestconfAppTest)  Time elapsed: 1.075 s  <<< FAILURE!
[INFO] java.lang.AssertionError: expected:<200> but was:<401>
[INFO]  at io.lighty.kit.examples.community.CommunityAAARestconfAppTest.readDataCorrectCredentials(CommunityAAARestconfAppTest.java:54)
[INFO] 
[INFO] [INFO] 
[INFO] [INFO] Results:
[INFO] [INFO] 
[INFO] [ERROR] Failures: 
[INFO] [ERROR]   CommunityAAARestconfAppTest.readDataCorrectCredentials:54 expected:<200> but was:<401>
[INFO] [INFO] 
[INFO] [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0

```

**Branch**
14.2.x

**To Reproduce**
1. git checkout https://...
2. cd lighty
3. mvn release:prepare

**Expected behavior**
Execution of release:prepare finishes successfully.

**Environment (please complete the following information):**
 - OS: Linux nitebug.nitenet.local 5.13.12-200.fc34.x86_64 #1 SMP Wed Aug 18 13:27:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Java Version
   openjdk version "11.0.12" 2021-07-20
   OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
   OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode, sharing)
 - Maven version
   Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
   Maven home: /home/nite/local/apache-maven-3.8.2
   Java version: 11.0.12, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.12.0.7-0.fc34.x86_64
   Default locale: en_GB, platform encoding: UTF-8
   OS name: "linux", version: "5.13.12-200.fc34.x86_64", arch: "amd64", family: "unix"

**Comment by vainyksi** [comment]
Closing as can not reproduce on latest 14.2.x, as well as `mvn release:prepare` successfully finished for recent release 14.2.1
```
[INFO] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.668 s - in io.lighty.kit.examples.community.CommunityAAARestconfAppTest
```
