### ISSUE TITLE
gNMI simulator: Unable to update data by its path

### ISSUE THREAD

**Issue by Fenrock** [PANTHEONtech/lighty#849]
### Describe the bug
Unable to update data using its path.
 Error : Schema for node with name network-instance and namespace http://openconfig.net/yang/network-instance does not exist at list network-instance

### Branch
15.0.1

### To Reproduce
Start gNMI simulator with these yang files:
[yangs.zip](https://github.com/PANTHEONtech/lighty/files/7520176/yangs.zip)
Send gNMI set request 
**Payload**
{
    "openconfig-network-instance:network-instance": [
    {
        "config": {
        "name": "Vlan10",
        "type": "openconfig-network-instance-types:L2L3"
        },
    "name": "Vlan10",
    "vlans": {
        "vlan": [
        {
            "config": {
            "name": "Vlan10",
            "vlan-id": 10
            },
            "vlan-id": 10
        }
        ]
    }
    }
    ]
}
**Request**
gnmi set --update-path /openconfig-network-instance:network-instances/network-instance[name=Vlan10] --update-file $file --encoding json_ietf

### Expected behavior
Successful gnmi request

### Environment 
 - Java Version 11
 - Maven version 3.6.3

**Comment by PeterSuna** [comment]
Hello Fenrock,
Inside payload, you have superfluous array openconfig-network-instance:network-instance. Try this:

**gnmic request**
`gnmic set --update-path "/openconfig-network-instance:network-instances/network-instance[name=Vlan10]" --update-file network_instance.json --encoding json_ietf`

**network_instance.json body**
`
{
    "config": {
        "name": "Vlan10",
        "type": "openconfig-network-instance-types:L2L3"
    },
    "name": "Vlan10",
    "vlans": {
        "vlan": [
            {
                "config": {
                    "name": "Vlan10",
                    "vlan-id": 10
                },
                "vlan-id": 10
            }
        ]
    }
}
`


Hope this helps.
