### ISSUE TITLE
buggy Netconf ODL dependency version 2.0.9 (fixed in 2.0.11)

### ISSUE THREAD

**Issue by guillaumelambert** [PANTHEONtech/lighty#888]
Netconf  ODL dependency currently in version 2.0.9 triggers the [ODL bug NETCONF-835](https://jira.opendaylight.org/browse/NETCONF-835), making part of logs totally unreadable (hexadecimal log messages).
netconf version >=2.0.11 have fixed this bug and shoud be preferred

**Branch**
15.1.x and  master

**Comment by vainyksi** [comment]
Fixed in `master` & `15.1.x`
Thank you Guillaume for the contribution
