### ISSUE TITLE
Lighty.io couldn't respond after one fail post operation

### ISSUE THREAD

**Issue by MuhendisBey** [PANTHEONtech/lighty#948]
**Describe the bug**
If registered device is not up. i mean link/connection which is between device and lighty is down. if lighty.io tries to submit a operation such as put/post. Even if connection is recovered. Lighty.io doesn't send success post/put operation till restart the lighty.io or de-register/register device.

**Branch**
15.1.0

**To Reproduce**
1. install the lighty 15.1.0 version
2. register a device
3. set a leaf over the swagger UI (post or put operation)
4. get success message
5. down the registered device (not deregister)
6. repeat step 3 many times
7. get fail message
8. bring up the registered device
9. repeat step 3

**Expected behavior**
user couldn't get fail message

**Actual behavior**
user get fail message

**Environment (please complete the following information):**
 - OS: debian 11
 - jre-11
 - maven 3.x

**Comment by MuhendisBey** [comment]
anyone can help me ? 
thank you in advance.

**Comment by ihrasko** [comment]
@MuhendisBey What is the fail message?

**Comment by ugurkaraca3** [comment]
Hello everyone,
This issue tested on 15.2.1, it is solved.

**Comment by MuhendisBey** [comment]
thx @ugurkaraca3, also it's solved in v16.0.0.
we can close this issue @ihrasko 

Many thx again.
