### ISSUE TITLE
"RemoteDevice{yuma}: No more sources for schema context",

### ISSUE THREAD

**Issue by MuhendisBey** [PANTHEONtech/lighty#953]
**Question**
How can i add device as a node into the lighty.io

Hello All,

I have been working with lighty.io for long time. Till that moment, i added many device as a node. But nowadays, i'm working on yumawork sdk. But I couldn't add it into the lighy.io.

it gives error like this:
![image](https://user-images.githubusercontent.com/10077290/163261925-db4c85cd-3a95-461a-a077-8bcdcd7c4ae8.png)

What should i check in that case, do u have suggestion?

Many thanks in advance,
Have a nice and healthy day,
With My Best Regards,
Onur.

**Comment by MuhendisBey** [comment]
Anybody can help ?

**Comment by mmiklus** [comment]
Can you attach all announced capabilities in the hello message and the list of YANG models provided by ietf-netconf-monitoring, please ?

**Comment by MuhendisBey** [comment]
```
Can you attach all announced capabilities in the hello message and the list of YANG models provided by ietf-netconf-monitoring, please ?
```
Yeah sure,
Here is the full output. (BTW, i tried with karaf-0.8.4, i can register successfully to ODL. There is broken somethin in next version.)
```
2022-04-16T19:25:13.010212216Z  WARN [default-pool-5-2] (DeviceSourcesResolver.java:60) - RemoteDevice{yuma-docker}:
Netconf device does not provide all yang models reported in hello message capabilities, required but not provided:
[(urn:ietf:params:xml:ns:yang:yumaworks-restconf?revision=2017-07-03)yumaworks-restconf,
(urn:ietf:params:xml:ns:yang:ietf-restconf-monitoring?revision=2017-01-26)ietf-restconf-monitoring,
(urn:ietf:params:xml:ns:netconf:notification:1.0?revision=2013-03-15)notifications,
(urn:ietf:params:xml:ns:yang:ietf-netconf-acm?revision=2018-02-14)ietf-netconf-acm,
(urn:ietf:params:xml:ns:yang:iana-crypt-hash?revision=2014-08-06)iana-crypt-hash,
(http://yumaworks.com/ns/yumaworks-extensions?revision=2021-12-14)yumaworks-extensions,
(urn:ietf:params:xml:ns:netconf:base:1.0?revision=2011-06-01)ietf-netconf,
(urn:ietf:params:xml:ns:yang:yang-data-ext?revision=2017-07-03)yang-data-ext,
(http://yumaworks.com/ns/yumaworks-event-stream?revision=2021-05-15)yumaworks-event-stream,
(http://yumaworks.com/ns/yumaworks-getbulk?revision=2021-08-07)yumaworks-getbulk,
(http://netconfcentral.org/ns/yuma-time-filter?revision=2012-11-15)yuma-time-filter,
(urn:ietf:params:xml:ns:yang:ietf-yang-structure-ext?revision=2020-06-17)ietf-yang-structure-ext,
(http://yumaworks.com/ns/yumaworks-app-common?revision=2021-08-24)yumaworks-app-common,
(urn:ietf:params:xml:ns:yang:ietf-inet-types?revision=2013-07-15)ietf-inet-types,
(http://yumaworks.com/ns/yumaworks-event-filter?revision=2014-02-09)yumaworks-event-filter,
(urn:ietf:params:xml:ns:yang:ietf-restconf?revision=2017-01-26)ietf-restconf,
(http://www.yuma.com/ns/example/config-types?revision=2019-02-14)config-types,
(urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?revision=2010-10-04)ietf-netconf-monitoring,
(urn:ietf:params:xml:ns:yang:ietf-yang-types?revision=2013-07-15)ietf-yang-types,
(http://yumaworks.com/ns/yumaworks-system?revision=2022-01-27)yumaworks-system,
(http://netconfcentral.org/ns/yuma-ncx?revision=2015-10-16)yuma-ncx,
(http://yumaworks.com/ns/yumaworks-ids?revision=2014-07-12)yumaworks-ids,
(urn:ietf:params:xml:ns:yang:yumaworks-support-save?revision=2017-07-27)yumaworks-support-save,
(http://yumaworks.com/ns/yumaworks-term-msg?revision=2019-05-05)yumaworks-term-msg,
(urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?revision=2012-02-06)ietf-netconf-notifications,
(http://www.yuma.com/ns/example/config?revision=2019-02-14)config,
(http://netconfcentral.org/ns/yuma-app-common?revision=2017-07-25)yuma-app-common,
(http://yumaworks.com/ns/yumaworks-templates?revision=2017-02-20)yumaworks-templates,
(urn:ietf:params:xml:ns:netconf:partial-lock:1.0?revision=2009-10-19)ietf-netconf-partial-lock,
(urn:ietf:params:xml:ns:yang:ietf-yang-library?revision=2016-06-21)ietf-yang-library,
(http://netconfcentral.org/ns/yuma-types?revision=2019-11-29)yuma-types,
(urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?revision=2011-06-01)ietf-netconf-with-defaults,
(urn:ietf:params:xml:ns:netmod:notification?revision=2008-07-14)nc-notifications,
(urn:ietf:params:xml:ns:yang:ietf-yang-patch?revision=2017-02-22)ietf-yang-patch,
(http://yumaworks.com/ns/yumaworks-types?revision=2021-05-15)yumaworks-types]
```

**Comment by mmiklus** [comment]
You can try to force capabilities and provide YANG models by using schema cache folder. 
More information: https://docs.opendaylight.org/projects/netconf/en/v2.0.14/user-guide.html#connecting-to-a-device-not-supporting-netconf-monitoring

Hope this helps.

**Comment by MuhendisBey** [comment]
Hello @mmiklus 

yeah u're right.
by following this: : https://docs.opendaylight.org/projects/netconf/en/v2.0.14/user-guide.html#connecting-to-a-device-not-supporting-netconf-monitoring,
i can add device successfully, but that is not fit to me. I need to register a device without any manual operations. So, i want to understand that what is the root cause?

Many Thanks again,
With My best Regards,

**Comment by PeterSuna** [comment]
Hello @MuhendisBey
I have started [Yumaworks netconfd-pro](https://www.yumaworks.com/pub/latest/install/yumapro-installation-guide.html#start-netconfd-pro) server and successfully connected to [RNC app example](https://github.com/PANTHEONtech/lighty/tree/15.2.0/lighty-applications/lighty-rnc-app-aggregator/lighty-rnc-app) and also [Lighty Actions App example](https://github.com/PANTHEONtech/lighty/tree/15.2.0/lighty-examples/lighty-community-restconf-actions-app) in version 15.2.0 and 16.0.0.

Please try this with latest released versions.

I hope this helps.

**Comment by MuhendisBey** [comment]
Hello @PeterSuna 

Thx for your effort Ii am really appreciate.
But i couldn't figure out to solve it. I have tried with 15.2.0, 16.0.0 16.1.0. But result is the same.
I believe in you, it should work in latest version. There should be a difference.
maybe, you are executing netconfd-pro with different parameter or something like that?
i'm sarting netconfd-pro like this :
netconfd-pro --log-level=debug4 --access-control=off

What do you think?
if you want, i can provide a repo for bringing up netconfd-pro.

Many thanks again,
i know that you hard worked for releasing v16.0.0
Many thanks for that,
With My Best Regards,
Onur.

**Comment by PeterSuna** [comment]
Hello @MuhendisBey
 my apologies, when I tried this first time with version 16.0.0 and 15.2.0 I was able to connect this device.
  
![yumma_log_LI](https://user-images.githubusercontent.com/20340119/170677550-485d8935-b22e-47ab-9135-11970f7203d6.jpg)

 When I tried this after, I've got same issue as you mentioned. What I found out is that model `yumaworks-support-save` provided by yumaworks netconf-pro server is not valid with current RFC7950. But, It seems the spec is rather bad and based on [this NETCONF WG thread](https://mailarchive.ietf.org/arch/msg/netconf/PxCbSq6rp5Sj0C2ylhzqeQrH2vo/) the intent is that "container data node definition" be NOT interpreted with RFC7950 terminology. More information you can find in ODL Jira issue: https://jira.opendaylight.org/browse/YANGTOOLS-1443.
  
If this will be resolved in ODL, the next lighty release with this fix should solve your issue.

**Comment by MuhendisBey** [comment]
@PeterSuna 
pls don't worry, no sorry :-) Always, we can face with that situation. The point is negations :-)

Cool, then we will wait for the solution of issue 1443.
At least, we have addressed the problem.

Have nice and healthy day.
Btw, I'm looking forward to get new release :-)

**Comment by PeterSuna** [comment]
Hello @MuhendisBey, 
when the issue I have mentioned above is solved. There is also a problem with netconf-monitoring response from yumaworks netconf-pro server. If you try to connect yumaworks netconf-pro server to lighty, currently is required to connect this device as if it did not support netconf-monitoring.  So you need to add yang models required by capabilities to cache/schema folder in lighty root. This is due to yumaworks netconf-pro server sending augmented NETCONF monitoring data.
```xml
   <schema>
     <identifier>ietf-netconf-partial-lock</identifier>
     <version>2009-10-19</version>
     <format xmlns:ncm="ses_msg: send 1.1 buff:988for s:3trace_buff: #982 ietf:params:xml:ns:yang:ietf-netconf-monitoring">ncm:yang</format>
     <namespace>urn:ietf:params:xml:ns:netconf:partial-lock:1.0</namespace>
     <location>NETCONF</location>
     <conformance xmlns="http://yumaworks.com/ns/yumaworks-system">true</conformance>
     <module-type xmlns="http://yumaworks.com/ns/yumaworks-system">module</module-type>
 </schema>
 ```

ODL NETCONF uses strict parsing for this response, so converting this message will fail, and no models will be downloaded from the device. Therefore, it will fail to create Schema context unless required models are provided inside cache/schema folder. I have created improvement for this to ODL NETCONF https://jira.opendaylight.org/browse/NETCONF-881

If you will be interested in using [OpenYuma](https://github.com/OpenClovis/OpenYuma), I was able to connect this device to lighty.

Thanks and best regards.

**Comment by marchest** [comment]
Hi @PeterSuna , @MuhendisBey,

I tried to add yumapro server to lighty 17.0 version. And I am able to add successfully without overriding capabilities. However, there are still error logs appears as @PeterSuna mentioned due to issue [https://jira.opendaylight.org/browse/YANGTOOLS-1443](https://jira.opendaylight.org/browse/YANGTOOLS-1443) here. This issue status seems resolved but as far as I understand lighty 17.0 does not include this fix. If so when we can see this fix in lighty release ?

Thanks,

**Comment by ihrasko** [comment]
Hi @marchest @MuhendisBey The fix is planned to be available in Lighty.io 16.3.0 and 17.1.0 releases.

Stay tuned!

**Comment by ihrasko** [comment]
lighty.io 16.3.0 has been released!
Enjoy!

**Comment by ihrasko** [comment]
lighty.io 17.1.0 has been released!
Enjoy!

**Comment by marchest** [comment]
Thanks @ihrasko
